### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by webdev522** [gladchinda/keygen-php#1]
Hello Glad Chinda.

I've read your tutorial - "Laravel Random Keys with Keygen" on scotch.io.
It is very useful for my laravel project for security.

But unfortunately, there is an error during the installing composer.
Please help me.
I've already installed laravel 5.3.* and then run next command.

--- error details ---
composer require gladcodes/keygen.

Using version ^1.0 for gladcodes/keygen
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing gladcodes/keygen (1.0.0)
    Downloading: 100%         

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                                   
  [ErrorException]                                                 
  The use statement with non-compound name 'Keygen' has no effect  
                                                                   

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
=====================================================
Thanks

**Comment by gladchinda** [comment]
The problem obviously isn't from the Keygen package. It is from your application code. Scan thoroughly for every use statement that refers to Keygen and add a backslash before the Keygen.
