### ISSUE TITLE
Can it generate the same number?

### ISSUE THREAD

**Issue by JackDPro** [gladchinda/keygen-php#5]
Can it generate the same number? I want to use it to generate user`s id. Thanks very much.

**Comment by gladchinda** [comment]
@dongkaipo There is a possibility that it can generate the same number. Although using a big length can reduce the chances, I would advise you check that the number is unique first

**Comment by gladchinda** [comment]
@dongkaipo The next release (still on the pipeline) has a feature called key exclusions, which allows you to blacklist keys from being generated. With that you should:
- Create a single generator instance
- Add each key you generate to the exclusions collection of the generator to prevent generating it again.

See the `v1.2.0-alpha` branch for more details.
