### ISSUE TITLE
alphanum error when length is 5 or less

### ISSUE THREAD

**Issue by ali-shabani** [gladchinda/keygen-php#6]
I try to generate random string with alphanum method but if I pass number smaller than 6 it generate error that say ErrorException: mt_rand(): max(-1) is smaller than min(0).
I think this should be ok if I want to generate random string with even length 1

**Comment by gladchinda** [comment]
@pyramid-ali that issue has been fixed on the new alpha branch of the package: `v1.2.0-alpha`

**Comment by gladchinda** [comment]
Try installing the new version using the following command:
```shell
$ composer require gladcodes/keygen dev-v1.2.0-alpha
```

**Comment by gladchinda** [comment]
@pyramid-ali in case you don't want to try the `dev-v1.2.0-alpha` version of the branch yet but want to continue using the current stable version, you can apply the following patch to the AlphaNumericGenerator.

Look for `Line 35` of the **keygen/src/Keygen/Generators/AlphaNumericGenerator.php** file and modify it as follows.

**Current**
```php
$chunkSize = $splitSize + mt_rand(1, 5);
```

**Modified**
```php
$chunkSize = 5 + $splitSize + mt_rand(1, 5);
```
